# -*- mode: ruby -*-
# vi: set ft=ruby :

#PROXY = "http://user:passwd@proxy.example.com"
#NOPROXY = "localhost,127.0.0.1,example.com"

Vagrant.configure("2") do |config|
  #config.proxy.http     = PROXY
  #config.proxy.https    = PROXY
  #config.proxy.no_proxy = NOPROXY
  config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vbguest.auto_update = false
  config.ssh.insert_key = false
  config.vm.box = "centos/7"
  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    vb.memory = "512"
    vb.name = "centos7"
  end

  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  #config.vm.provision "shell", inline: <<-SHELL
    # Shell Examples, setting up smb credentials
    # printf "username=user\npassword=passwd" > /etc/smbcred
    # yum -y update
    # yum -y install cifs-utils
  #SHELL
#end
